<?php
date_default_timezone_set('Asia/Manila');
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
function emailing($messageVar){
#GENERATING EMAIL NOTIFICATION
                
                      require 'phpmailer/src/Exception.php';
                      require 'phpmailer/src/PHPMailer.php';
                      require 'phpmailer/src/SMTP.php';

                        $mail = new PHPMailer(true);
                         
                          $mail->isSMTP();
                          $mail->Host = "smtp.gmail.com"; // mail.madasikinara.com
                          $mail->SMTPAuth = true;
                          $mail->Username = "johnlouisuru@gmail.com"; //jlouisuru@gmail.com
                          $mail->Password = "lgdp gxht jftm nqyt"; //ttqm fhro jntr ozcx
                          $mail->SMTPSecure = 'ssl'; //ssl
                          $mail->Port = 465; //465
                          $mail->setFrom("johnlouisuru@gmail.com"); //jlouisuru@gmail.com

                          $mail->addAddress("jlouisuru@gmail.com"); // ito ang recipient 
                        
                          #THIS IS FOR LOCAL VERSION

                        $mail->isHTML(true);

                        $mail->Subject = "TRAINEE`s STATUS MONITORING SYSTEM: ".$messageVar.".";
                        $mail->Body = "
                        <h3>[".$messageVar."] Trainees` Status Monitoring System as of (".date("d-M-Y Hi")."H).
                        </h3>
                        <br />
                        <hr />
                        <p>
                        This is an Automatic E-mail generated by the Trainees Status Monitoring System. <br /> Refrain from Replying. Thank you.
                        </p>
                        <a href='http://localhost/acad/dashboard.php'>
                        Click here to check the file. 
                        </a>
                        ";

                        /*$data['message'] = $mail->ErrorInfo;
                        echo json_encode($data);
                        die();*/
                        //$data['message'] = "<p class='alert alert-success'> ".$_POST['rank_']." ".$_POST['fullname_']."Successfully Added</p>";
                        //echo json_encode($data);
                        //die();
                        //$data['message'] = "<p class='alert alert-success'> ".$_POST['rank_']." ".$_POST['fullname_']."Successfully Added</p>"; 
                        /*$data['message'] = "<p class='alert alert-success'> ".$_POST['rank_']." ".$_POST['fullname_']." Successfully Added</p>";
                        echo json_encode($data);
                        die(); */
                        if($mail->send()){  
                          $data['message'] = '<p class="alert alert-success">'.$messageVar.' </p>'; 
                           
                        }
                        else {
                          $data['message'] = '<p class="alert alert-danger">Error 404: Please Contact your Handsome Developer.</p>';
                          
                        }

                #GENERATING EMAIL NOTIFICATION ENDDDD
  }
?>