<?php
date_default_timezone_set('Asia/Manila');
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
function emailing($messageVar,$email){
#GENERATING EMAIL NOTIFICATION
                
                      require 'phpmailer/src/Exception.php';
                      require 'phpmailer/src/PHPMailer.php';
                      require 'phpmailer/src/SMTP.php';

                        $mail = new PHPMailer(true);
                         
                          $mail->isSMTP();
                          $mail->Host = "smtp.gmail.com"; // mail.madasikinara.com
                          $mail->SMTPAuth = true;
                          $mail->Username = "johnlouisuru@gmail.com"; //jlouisuru@gmail.com
                          $mail->Password = "lgdp gxht jftm nqyt"; //ttqm fhro jntr ozcx
                          $mail->SMTPSecure = 'ssl'; //ssl
                          $mail->Port = 465; //465
                          $mail->setFrom("johnlouisuru@gmail.com"); //jlouisuru@gmail.com

                          $mail->addAddress($email); // ito ang recipient 
                        
                          #THIS IS FOR LOCAL VERSION

                        $mail->isHTML(true);

                        $mail->Subject = "Your CHAD Auto Generated Password";
                        $mail->Body = "
                        <h3>CHAD Elevator System as of (".date("d-M-Y H:i:s A").").
                        </h3>
                        <p>$messageVar</p>
                        <br />
                        <hr />
                        <p>
                        This is an Automatic E-mail generated by the CHAD Elevator System. <br /> Refrain from Replying. Thank you.
                        </p>
                        ";
                        if($mail->send()){  
                          $data['message'] = '<p class="alert alert-success"> Password Sent </p>'; 
                           
                        }
                        else {
                          $data['message'] = '<p class="alert alert-danger">Error 404: Please Contact your Developer.</p>';
                          
                        }

                #GENERATING EMAIL NOTIFICATION ENDDDD
  }
?>