<?php 

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
require("db/conn.php");
/*if(!@$_SESSION['office']){
	header('Location: login.php');
  die();
}*/
?>

<!DOCTYPE html>
<html lang="en">

<head>
  <?php
    require('head.php');
  ?>
</head>

<body class='toggle-sidebar'>

  <main id="main" class="main">

<?php 
//if(isset($_POST['submit'])){
  //echo "Aym Fayn!";
	$tobe_uploaded = '';
// If so, then i have to set the uploads path.
$folder = "orders/";
//$target_file = $folder . basename($_FILES["fileName"]["name"]);
// The $_FILES variable holds a multidimensional array.
// That means that each image property is an array.
// In order to store the images in our folder, i need
// the image name, and the temporary stored location.
$names = $_GET['orig_name']; // The $names variable will hold an array
// of the images names;

$tmp_names = $_GET['tmp_name']; // And the $tmp_names holds

$is_nhq = $_GET['is_nhq'];
$authority = '';
//move_uploaded_file($tmp_names, $target_file);
$query2 = mysqli_query($db,"INSERT INTO orders(orig_name,tmp_name,remarks,is_nhq)
                              VALUES('$names','$tmp_names','','$is_nhq')");
if($query2){
  if($is_nhq == 1){
    $authority = 'NHQ';
  }
  else {
    $authority = 'HCGETDC';
  }

  #GENERATING NOTIFICATION FOR THE ORIGINATING OFFICE
                /*$insert_notification = "<p><b>".$_POST['ref_num']."</b> moved to <b>".$xoff."</b> Office.</b><br>
                        Received by: <u>".$_POST['rcvd']."</u><br>
                        ".date("d-M-Y H:i")."H
                        </p>";
                $notifs = "INSERT INTO notifs(message,office_id,req_id)
                                        VALUES('$insert_notification','$_POST[orig_ofc]','$x3')";
                      if(mysqli_query($db,$notifs)){
                        $notification_message = 'The Originating Office has been Notified.';
                      }*/
                      require 'phpmailer/src/Exception.php';
                      require 'phpmailer/src/PHPMailer.php';
                      require 'phpmailer/src/SMTP.php';

                        $mail = new PHPMailer(true);

                        #THIS IS FOR ONLINE VERSION 
                        
                        /*$mail->isSMTP();
                        $mail->Host = "mail.madasikinara.com";
                        $mail->SMTPAuth = true;
                        $mail->Username = "owlsystem@madasikinara.com";
                        $mail->Password = "q7XB-2iY=WBa";
                        $mail->SMTPSecure = 'ssl';
                        $mail->Port = 465;

                        $mail->setFrom("owlsystem@madasikinara.com");

                        $mail->addAddress('jlouisuru@gmail.com');*/

                        #THIS IS FOR ONLINE VERSION

                        #THIS IS FOR LOCAL VERSION
                         
                          $mail->isSMTP();
                          $mail->Host = "smtp.gmail.com";
                          $mail->SMTPAuth = true;
                          $mail->Username = "johnlouisuru@gmail.com";
                          $mail->Password = "mmqqwimykgjpnwoh";
                          $mail->SMTPSecure = 'ssl';
                          $mail->Port = 465;

                          $mail->setFrom("johnlouisuru@gmail.com");

                          $mail->addAddress("jlouisuru@gmail.com");
                        
                          #THIS IS FOR LOCAL VERSION

                        $mail->isHTML(true);

                        $mail->Subject = "TRAINEE MONITORING PLATFORM: ".$names." has been uploaded.";
                        $mail->Body = "
                        <h3>The File <i>$names</i> has been Uploaded by the CGETDC Administrator. The uploaded file is in the
                        <u>$authority</u> Authority Level. Sent as of Today (".date("d-M-Y H:i")."H).
                        </h3>
                        <br />
                        <hr />
                        <p>
                        This is an Automatic E-mail generated by the Trainee Monitoring Platform. <br /> Refrain from Replying. Thank you.
                        </p>
                        <a href='http://localhost/acad/upload.php'>
                        Click here to check the file. 
                        </a>
                        ";

                        if($mail->send()){  
                          echo "<div class='alert alert-success'><span class='bi bi-check'></span> Your File <b>$names</b> Successfully Uploaded. Email Notification has been sent.</div>";         
                        }
                        else {
                          echo "<div class='alert alert-danger'>Mailer error: " . $mail->ErrorInfo . "</div>";
                        }
                #GENERATING EMAIL NOTIFICATION ENDDDD




  
  //header("Location: https://www.madasikinara.com/owlsystem/localuploads.php?orig_name=$names&tmp_name=$tmp_names");
  //die();
  ?>
  <?php
}
else {
  echo "<div class='alert alert-danger'><span class='bi bi-x-circle-fill'></span> Your File <b>$names</b> Encountered an Error.</div>";
}
          
    
/*}
else {

}*/
?>
<a href="upload.php" type="button" class="btn btn-primary bi bi-arrow-left"> Back</a>
</main>

</body>
</html>
